const productos = [
    {
        id: 1,
        nombre: 'Nike V2K Run',
        categoria: 'Zapatillas para mujer',
        precio: 'S/ 599.90',
        tallas: ['5.5','6','6.5','7','7.5','8','8.5','9'],
        etiquetas: ['Mujer'],
        descripcion: 'Adelanta. Regresa. No importa, este calzado lleva lo retro al futuro. El V2K remasteriza todo lo que amas del Vomero con un look traído directamente de un catálogo de running de principios de siglo. Equípate con una combinación de elementos metalizados llamativos, malla transpirable y una entresuela con una estética perfectamente vintage. La entresuela de espuma de doble densidad y el talón estilo chunky garantizan comodidad vayas donde vayas.',
        detalle:'',
        datos_producto:'',
        colorMuestra:'Blanco Cumbre/Blanco/Marrón Verdoso Claro/Cromo',
        estilo:'FN6703-100',
        imagenes:["",""]
    },
    {
        id: 2,
        nombre: 'Nike V2K Run',
        categoria: 'Zapatillas para hombre',
        precio: 'S/ 569.90',
        tallas: ['6','6.5','7','7.5','8','8.5','9','9.5','10','10.5','11','11.5','12','12.5','13','14','15'],
        etiquetas: ['Hombre'],
        descripcion: 'Adelanta. Regresa. No importa, este calzado lleva lo retro al futuro. El V2K remasteriza todo lo que amas del Vomero con un look traído directamente de un catálogo de running de principios de siglo. Equípate con una combinación de elementos metalizados llamativos, detalles de plástico referenciales y una entresuela con una estética perfectamente vintage. Y el talón estilo chunky garantiza comodidad vayas donde vayas.',
        detalle:'',
        datos_producto:'',
        colorMuestra:'Verde Vintage/Pícea Mineral/Gris Lobo/Verde Vintage',
        estilo:'HJ4497-300',
        imagenes:["",""]
    },
    {
        id: 3,
        nombre: 'Nike Zoom Vomero 5',
        categoria: 'Zapatillas para mujer',
        precio: 'S/ 789.90',
        tallas: ['5.5','6','6.5','7','7.5','8','8.5','9'],
        etiquetas: ['Mujer'],
        descripcion: 'Forja un nuevo camino con el Zoom Vomero 5: tu favorito por su diseño complejo, profundo y fácil de combinar. Este calzado presume una estética vintage que es un toque retro perfecto de los runners de principios de siglo. El diseño de ricas capas incluye telas, cuero y detalles plásticos que se unen para crear uno de los calzados más geniales de la temporada.',
        detalle:'',
        datos_producto:'',
        colorMuestra:'Platino Puro/Marrón Verdoso Claro/Gris Lobo/Cromo',
        estilo:'FN6742-002',
        imagenes:["",""]
    },
    {
        id: 4,
        nombre: 'Nike Zoom Vomero 5',
        categoria: 'Zapatillas para hombre',
        precio: 'S/ 749.90',
        tallas: ['7','7.5','8','8.5','9','9.5','10','10.5','11','12'],
        etiquetas: ['Hombre'],
        descripcion: 'Forja un nuevo camino con el Zoom Vomero 5: tu favorito por su diseño complejo, profundo y fácil de combinar. El diseño de ricas capas incluye telas, cuero y detalles plásticos que se unen para crear uno de los calzados más geniales de la temporada.',
        detalle:'',
        datos_producto:'',
        colorMuestra:'Marrón Verdoso Claro/Marrón Verdoso Claro',
        estilo:'HF1553-100',
        imagenes:["",""]
    },
    {
        id: 5,
        nombre: 'Nike Air Force 1 Dance',
        categoria: 'Zapatillas para mujer',
        precio: 'S/ 679.90',
        tallas: ['5','5.5','6','6.5','7','7.5','8','8.5','9','9.5','10','10.5'],
        etiquetas: ['Mujer'],
        descripcion: 'Estos Air Force 1 están diseñados para el movimiento. Diseñados para satisfacer las necesidades de los bailarines, esta versión incluye amortiguación Air en el antepié para ofrecer una sujeción personalizable. La parte superior anatómica con una zona del tobillo más gruesa ayuda a sujetar el mediopié y el talón y que la suela exterior más flexible permite mostrar tu juego de pies con facilidad.',
        detalle:'',
        datos_producto:'',
        colorMuestra:'Summit White/Polvo De Fotones/Plata Metalizado',
        estilo:'FJ7409-101',
        imagenes:["",""]
    },
    {
        id: 6,
        nombre: 'Nike Cortez Leather',
        categoria: 'Zapatillas para mujer',
        precio: 'S/ 399.90',
        tallas: ['5.5','6','6.5','7','7.5','8','8.5','9','9.5','10'],
        etiquetas: ['Mujer'],
        descripcion: 'Una palabra: tradición. Desde la actividad clásica de salir a correr hasta el fenómeno de la moda, siempre está presente el encanto retro de los Cortez, su entresuela suave como una esponja y sus detalles dentados, que se mantienen década tras década. Esta versión de cuero crea un look premium ganador.',
        detalle:'',
        datos_producto:'',
        colorMuestra:'Blanco/Vela/Oro Metalizado/Obsidiana',
        estilo:'HJ9343-100',
        imagenes:["",""]
    },
    {
        id: 7,
        nombre: 'Nike Court Royale 2 Low',
        categoria: 'Zapatillas para hombre',
        precio: 'S/ 229.90',
        tallas: ['7','7.5','8','8.5','9','9.5','10','10.5','11','11.5','12','13'],
        etiquetas: ['Hombre'],
        descripcion: 'El Nike Court Royale 2, que es un auténtico legado del pasado, posee el mismo diseño que ha tenido tanto éxito en las calles desde finales de los 70. La parte superior de cuero es llamativa y fácil de llevar, mientras que el diseño grande del logotipo Swoosh le da un toque retro. Además, la suela con diseño de espiguilla aporta un giro al look clásico.',
        detalle:'',
        datos_producto:'',
        colorMuestra:'Blanco/Verde Azul Verdoso Oscuro',
        estilo:'CQ9246-105',
        imagenes:["",""]
    }
]

export default productos;